version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
jobs:
  unit-tests:
    docker:
      - image: circleci/node:10-browsers
        environment:
          TYPEORM_NAME: ci
      - image: circleci/postgres:11-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: linkstats_test
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}-{{checksum "client/yarn.lock" }}
      - run:
          name: Install Server Packages
          command: yarn install
      - run:
          name: Install Client Packages
          command: cd client && yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}-{{checksum "client/yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - /usr/local/share/.cache/yarn
      - run:
          name: Run Lint
          command: yarn lint
      - run:
          name: Run Server Tests
          command: yarn test-ci
      - run:
          name: Run Client Tests
          command: cd client && yarn test-ci
      - run:
          name: Run E2E Tests
          command: cd client && yarn build && cd .. && yarn test-ci:e2e
  build-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker build .

workflows:
  test:
    jobs:
      - unit-tests
      - build-image:
          filters:
            branches:
              ignore: master
      - aws-ecr/build_and_push_image:
          requires:
            - unit-tests
          filters:
            branches:
              only: master
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: ${AWS_DEFAULT_REGION}
          tag: "${CIRCLE_SHA1}"
